/*
	2025-05-16 v0.2 Adam
*/

DECLARE @ExtractDate DATETIME
SET @ExtractDate = GETDATE();

SELECT	
	Transaction_Serial_No AS 'Transaction_Serial_No',
	MTI AS 'MTI',
	PrimaryBitMap AS 'Primary Bit Map',
	SecondaryBitMap AS 'Secondary Bit Map',
	HashBytes('SHA2_256', Card_No) AS 'Card No',
	ProcessingCode AS 'Processing Code',
	Transaction_Amount AS 'Transaction Amount',
	ReconAmount AS 'Recon Amount',
	TransmisionDateTime AS 'Transmision Date and Time',
	STAN AS 'STAN',
	Transaction_Datetime AS 'Transaction Datetime',
	[Expiry_Date] AS 'Expiry Date',
	CaptureDate AS 'Capture Date',
	CountryCode AS 'Country Code',
	CardDataInputCapability AS 'Card Data Input Capability',
	CardholderAuthCapability AS 'Cardholder Auth Capability',
	CardCaptureCapability AS 'Card Capture Capability',
	OS AS 'OS',
	CardholderPresent AS 'Cardholder Present',
	CardPresent AS 'Card Present',
	CardInputMode AS 'Card Input Mode',
	CardholderAuthMethod AS 'Cardholder Auth Method',
	CardholderAuthEntity AS 'Cardholder Auth Entity',
	CardDataOutputCapability AS 'Card Data Output Capability',
	TerminalOutputCapability AS 'Terminal Output Capability',
	PINCaptureCapability AS 'PIN Capture Capability',
	HashBytes('SHA2_256', CardSequenceNo) AS 'Card Sequence No',
	FunctionCode AS 'Function Code',
	MessageReasonCode AS 'Message Reason Code',
	Merchant_Id AS 'MCC',
	AcquirerID AS 'AcquirerID',
	ForwardingID AS 'Forwarding ID',
	Track2 AS 'Track2',
	RRN AS 'RRN',
	ApprovalCode AS 'Approval Code',
	ActionCode AS 'Action Code',
	CardAcceptorTerminalID AS 'Card Acceptor Terminal ID',
	CardAcceptorIdCode AS 'Card Acceptor Id Code',
	HashBytes('SHA2_256', CardAcceptorName) AS 'Card Acceptor Name',
	HashBytes('SHA2_256', CardAcceptorStreet) AS 'Card Acceptor Street',
	CardAcceptorCity AS 'Card Acceptor City',
	CardAcceptorPostalCode AS 'Card Acceptor Postal Code',
	CardAcceptorRegionCode AS 'Card Acceptor Region Code',
	CardAcceptorCountryCode AS 'Card Acceptor Country Code',
	TransactionCurrencyCode AS 'Transaction Currency Code',
	ReconCurrencyCode AS 'Recon Currency Code',
	OriginalMTI AS 'Original MTI',
	OriginalSTAN AS 'Original STAN',
	OriginalTrxDatetime AS 'OriginalTrxDatetime',
	HashBytes('SHA2_256', OriginalAcquirerID) AS 'Original Acquirer ID',
	ReservedPrivate1 AS 'Reserved Private 1',
	HashBytes('SHA2_256', AccountIdentification1) AS 'Debit Account No',
	HashBytes('SHA2_256', AccountIdentification2) AS 'Credit Account No',
	ReservedPrivate2 AS 'Reserved Private 2',
	TransactionAmountIDR AS 'Transaction Amount IDR'
INTO [DataExtractionDB].[dbo].[C09_Details_Hashed]
FROM [BDI-PRD-PDTORDB].[Predator].[dbo].[C09_Details] WITH (NOLOCK) WHERE Transaction_Datetime <= @ExtractDate